/* Generated by cbindgen from geopackage-ffi. Do not edit by hand.
 *
 * Regenerate with:
 *     cbindgen --config geopackage-ffi/cbindgen.toml \
 *              --crate geopackage-ffi \
 *              --output geopackage-ffi/include/geopackage.h
 *
 * CI regenerates it and fails if the result differs from what is committed, so
 * an ABI change cannot land without showing up as a diff in this file.
 */

/* Conventions, assumed by every declaration below:
 *
 * - Strings are NUL-terminated UTF-8 in both directions. A returned char * is
 *   owned by the caller and released with gpkg_string_free; a string passed in
 *   is borrowed for the duration of the call.
 * - Every fallible call takes an optional gpkg_error_t * out-parameter, filled
 *   in on failure with a status code and an owned message that
 *   gpkg_error_clear releases. Pass NULL to receive only the return value.
 * - Handles are opaque and each has exactly one destructor. A container cannot
 *   be closed while a layer handle, a tiles handle or an Arrow stream taken
 *   from it is alive: gpkg_close refuses with GPKG_STATUS_HANDLE_IN_USE and
 *   changes nothing.
 * - Features are read as Arrow record batches, and written either way:
 *   gpkg_layer_write_arrow appends in bulk, and a gpkg_writer_t from
 *   gpkg_layer_writer inserts, updates and deletes a row at a time. There is
 *   no separate save step: a write is durable when its call returns, or at
 *   gpkg_commit inside an open transaction.
 * - One handle per thread. A handle may be created on one thread and used on
 *   another, but never used from two at once, and nothing is locked
 *   internally. For concurrent reads, open the file once per thread.
 */

#ifndef GEOPACKAGE_H
#define GEOPACKAGE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#ifndef ARROW_C_DATA_INTERFACE
#define ARROW_C_DATA_INTERFACE

#define ARROW_FLAG_DICTIONARY_ORDERED 1
#define ARROW_FLAG_NULLABLE 2
#define ARROW_FLAG_MAP_KEYS_SORTED 4

struct ArrowSchema {
  const char *format;
  const char *name;
  const char *metadata;
  int64_t flags;
  int64_t n_children;
  struct ArrowSchema **children;
  struct ArrowSchema *dictionary;
  void (*release)(struct ArrowSchema *);
  void *private_data;
};

struct ArrowArray {
  int64_t length;
  int64_t null_count;
  int64_t offset;
  int64_t n_buffers;
  int64_t n_children;
  const void **buffers;
  struct ArrowArray **children;
  struct ArrowArray *dictionary;
  void (*release)(struct ArrowArray *);
  void *private_data;
};

#endif  /* ARROW_C_DATA_INTERFACE */

#ifndef ARROW_C_STREAM_INTERFACE
#define ARROW_C_STREAM_INTERFACE

struct ArrowArrayStream {
  int (*get_schema)(struct ArrowArrayStream *, struct ArrowSchema *out);
  int (*get_next)(struct ArrowArrayStream *, struct ArrowArray *out);
  const char *(*get_last_error)(struct ArrowArrayStream *);
  void (*release)(struct ArrowArrayStream *);
  void *private_data;
};

#endif  /* ARROW_C_STREAM_INTERFACE */


/**
 * What kind of failure occurred.
 *
 * A small set of categories rather than one constant per library error, so
 * that a caller can branch on the code and read the message for the detail.
 * The values are assigned explicitly and are never reused for another meaning,
 * so a comparison written against this header keeps its meaning.
 */
enum gpkg_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * No error.
   */
  GPKG_STATUS_OK = 0,
  /**
   * The file could not be read or written: an I/O or SQLite failure.
   */
  GPKG_STATUS_IO = 1,
  /**
   * The file is not a GeoPackage, or not one this library can identify.
   */
  GPKG_STATUS_NOT_A_GEO_PACKAGE = 2,
  /**
   * A named table, layer, column, SRS or record is not there.
   */
  GPKG_STATUS_NOT_FOUND = 3,
  /**
   * Something the call would create is already there.
   */
  GPKG_STATUS_ALREADY_EXISTS = 4,
  /**
   * An argument was rejected: a bad value, a type mismatch, a malformed
   * geometry, or a count that does not line up.
   */
  GPKG_STATUS_INVALID_ARGUMENT = 5,
  /**
   * The file uses something this library does not implement.
   */
  GPKG_STATUS_UNSUPPORTED = 6,
  /**
   * A constraint the file or the schema declares was violated.
   */
  GPKG_STATUS_CONSTRAINT = 7,
  /**
   * A handle is still borrowing what the call would destroy. Free the child
   * handles first; nothing was changed.
   */
  GPKG_STATUS_HANDLE_IN_USE = 8,
  /**
   * A string argument was not valid UTF-8, or a required pointer was NULL.
   */
  GPKG_STATUS_BAD_ARGUMENT = 9,
  /**
   * Anything else. The message says what happened.
   */
  GPKG_STATUS_OTHER = 99,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum gpkg_status gpkg_status;
#else
typedef int32_t gpkg_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which case a [`gpkg_value_t`] holds.
 *
 * `#[repr(i32)]` so cbindgen emits a plain C enum with stable values. Values
 * are assigned explicitly and must never be reused for another meaning.
 */
enum gpkg_value_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * SQL `NULL`. The payload is not read.
   */
  GPKG_VALUE_KIND_NULL = 0,
  /**
   * A boolean, stored as `0` or `1`.
   */
  GPKG_VALUE_KIND_BOOLEAN = 1,
  /**
   * An integer of any declared width.
   */
  GPKG_VALUE_KIND_INTEGER = 2,
  /**
   * A floating-point number.
   */
  GPKG_VALUE_KIND_FLOAT = 3,
  /**
   * Text, as a NUL-terminated UTF-8 string the caller owns.
   */
  GPKG_VALUE_KIND_TEXT = 4,
  /**
   * Binary, as a pointer and a length the caller owns.
   */
  GPKG_VALUE_KIND_BLOB = 5,
  /**
   * A calendar date.
   */
  GPKG_VALUE_KIND_DATE = 6,
  /**
   * A date and time.
   */
  GPKG_VALUE_KIND_DATE_TIME = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum gpkg_value_kind gpkg_value_kind;
#else
typedef int32_t gpkg_value_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A `gpkg_t`: an open GeoPackage, and a count of the handles borrowing it.
 */
typedef struct gpkg_t gpkg_t;

/**
 * A `gpkg_layer_t`: a layer, and the container it borrows.
 */
typedef struct gpkg_layer_t gpkg_layer_t;

/**
 * A `gpkg_tiles_t`: a tile pyramid, and the container it borrows.
 */
typedef struct gpkg_tiles_t gpkg_tiles_t;

/**
 * A `gpkg_writer_t`: a write transaction over a layer, and the container it
 * borrows.
 *
 * Held by value rather than boxed, because unlike a container nothing borrows
 * *this*: the writer is the leaf of the handle graph.
 */
typedef struct gpkg_writer_t gpkg_writer_t;

/**
 * An open GeoPackage. Opaque; created by `gpkg_open`, `gpkg_open_read_only` or
 * `gpkg_create`, and destroyed by `gpkg_close`.
 */
typedef gpkg_t gpkg_t;

/**
 * A failure, as C sees it.
 *
 * Initialise one as `{GPKG_STATUS_OK, NULL}` and pass its address to any call
 * that takes a `gpkg_error_t *`. A successful call leaves it alone. A failing
 * one sets `code` and stores an owned, NUL-terminated UTF-8 `message`, which
 * the caller releases with `gpkg_error_clear` before reusing the variable.
 */
typedef struct {
  /**
   * What kind of failure occurred.
   */
  gpkg_status code;
  /**
   * A human-readable description, or NULL. Owned by the caller once set.
   */
  char *message;
} gpkg_error_t;

/**
 * A layer of an open GeoPackage. Opaque; created by `gpkg_layer_open` or
 * `gpkg_attributes_open`, and destroyed by `gpkg_layer_free`.
 */
typedef gpkg_layer_t gpkg_layer_t;

/**
 * A tile pyramid of an open GeoPackage. Opaque; created by `gpkg_tiles_open`
 * and destroyed by `gpkg_tiles_free`.
 */
typedef gpkg_tiles_t gpkg_tiles_t;

/**
 * A write transaction over one layer. Opaque; created by
 * `gpkg_layer_writer`, and destroyed by `gpkg_writer_commit` or
 * `gpkg_writer_free`.
 */
typedef gpkg_writer_t gpkg_writer_t;

/**
 * Binary data the caller owns: a pointer and a length.
 *
 * A length of zero is an empty blob, for which `data` may be NULL.
 */
typedef struct {
  /**
   * The bytes, read during the call that takes them.
   */
  const uint8_t *data;
  /**
   * How many bytes.
   */
  size_t len;
} gpkg_blob_t;

/**
 * A calendar date: year 0 to 9999, month 1 to 12, day 1 to the month's length.
 *
 * Checked when the value is read, so an impossible date is a rejected call
 * rather than a bad row.
 */
typedef struct {
  /**
   * Year, 0 to 9999. The four-digit text form is what bounds it.
   */
  uint16_t year;
  /**
   * Month, 1 to 12.
   */
  uint8_t month;
  /**
   * Day, 1 to the length of the month.
   */
  uint8_t day;
} gpkg_date_t;

/**
 * A date and time, with an optional UTC offset.
 *
 * `has_offset` false means the time carries no offset, which the spec permits
 * and which is not the same as an offset of zero: zero is `Z`.
 */
typedef struct {
  /**
   * The calendar date.
   */
  gpkg_date_t date;
  /**
   * Hour, 0 to 23.
   */
  uint8_t hour;
  /**
   * Minute, 0 to 59.
   */
  uint8_t minute;
  /**
   * Second, 0 to 59.
   */
  uint8_t second;
  /**
   * Sub-second component, 0 to 999 999 999.
   */
  uint32_t nanosecond;
  /**
   * Whether `offset_minutes` is to be read.
   */
  bool has_offset;
  /**
   * UTC offset in minutes. `0` with `has_offset` set is `Z`.
   */
  int16_t offset_minutes;
} gpkg_datetime_t;

/**
 * The payload of a [`gpkg_value_t`]. Which member is live is given by the
 * accompanying [`ValueKind`].
 */
typedef union {
  /**
   * Live for [`ValueKind::Boolean`].
   */
  bool boolean;
  /**
   * Live for [`ValueKind::Integer`].
   */
  int64_t integer;
  /**
   * Live for [`ValueKind::Float`].
   */
  double real;
  /**
   * Live for [`ValueKind::Text`]: NUL-terminated UTF-8.
   */
  const char *text;
  /**
   * Live for [`ValueKind::Blob`].
   */
  gpkg_blob_t blob;
  /**
   * Live for [`ValueKind::Date`].
   */
  gpkg_date_t date;
  /**
   * Live for [`ValueKind::DateTime`].
   */
  gpkg_datetime_t datetime;
} gpkg_value_payload;

/**
 * One cell of a row: a tag and a payload.
 *
 * Nothing here is owned by the library. Text and binary point at the caller's
 * memory and are read during the call that takes them.
 */
typedef struct {
  /**
   * Which case `value` holds.
   */
  gpkg_value_kind kind;
  /**
   * The payload. Read according to `kind`; not read at all for
   * [`ValueKind::Null`].
   */
  gpkg_value_payload value;
} gpkg_value_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open an existing GeoPackage read-write.
 *
 * The file is validated strictly: one that does not identify as a GeoPackage,
 * or that is missing a core table, is refused rather than opened.
 * `gpkg_open_read_only` is the tolerant counterpart.
 *
 * Returns NULL on failure, with `error` filled in when it is non-NULL.
 *
 * ```c
 * gpkg_error_t error = {GPKG_STATUS_OK, NULL};
 * gpkg_t *gpkg = gpkg_open("places.gpkg", &error);
 * if (!gpkg) {
 *     fprintf(stderr, "%s\n", error.message ? error.message : "(no message)");
 *     gpkg_error_clear(&error);
 *     return 1;
 * }
 * // ... work with the file ...
 * gpkg_close(gpkg, &error);
 * ```
 *
 * # Safety
 *
 * `path` must be a valid pointer to a NUL-terminated UTF-8 string. `error`
 * must be NULL or point at a writable `gpkg_error_t`. The returned handle must
 * be destroyed with `gpkg_close`, on the thread that created it.
 */
gpkg_t *gpkg_open(const char *path, gpkg_error_t *error);

/**
 * Open an existing GeoPackage read-only, tolerating legacy and lightly
 * non-conforming files.
 *
 * A reader that turned away the files worth reading would not be much use, so
 * this accepts what it can and records each thing it tolerated;
 * `gpkg_open_warning_count` and `gpkg_open_warning` report them. What it will
 * not tolerate is a file that fails to identify as a GeoPackage at all.
 *
 * The handle is read-only, so a write through it fails with `GPKG_STATUS_IO`
 * carrying SQLite's own message.
 *
 * # Safety
 *
 * As [`gpkg_open`].
 */
gpkg_t *gpkg_open_read_only(const char *path, gpkg_error_t *error);

/**
 * Create a new GeoPackage 1.4 file.
 *
 * The file is seeded with the two core tables and the spatial reference
 * systems the specification requires, and nothing else: a layer is added with
 * `gpkg_create_layer_from_arrow_schema`, and any other spatial reference
 * system with `gpkg_add_epsg_srs`.
 *
 * Fails with `GPKG_STATUS_ALREADY_EXISTS` when `path` is there and not empty,
 * so an existing file is never written over.
 *
 * # Safety
 *
 * As [`gpkg_open`].
 */
gpkg_t *gpkg_create(const char *path, gpkg_error_t *error);

/**
 * Close a GeoPackage and release its handle.
 *
 * Refuses with `GPKG_STATUS_HANDLE_IN_USE` while anything taken from it is
 * still alive, which means a layer handle, a tile pyramid handle or an Arrow
 * stream. In that case **the handle remains valid and open**, nothing has been
 * released, and the caller should free those children and call again. On any
 * other outcome the handle is destroyed and must not be used again, including
 * when this reports a failure: the underlying file was released either way.
 *
 * An open transaction is rolled back, because that is what SQLite does when a
 * connection goes. Commit before closing if the writes are to be kept.
 *
 * Closing does not rewrite the file's journal mode. This ABI opens with
 * whatever mode the file already has and never asks for WAL, so a file that
 * was a single file stays one, and a file already in WAL keeps its mode.
 *
 * ```c
 * gpkg_layer_free(layer);   // every child first
 * if (gpkg_close(gpkg, &error) != GPKG_STATUS_OK) {
 *     return fail("gpkg_close", &error);
 * }
 * ```
 *
 * # Safety
 *
 * `gpkg` must be a handle from one of the open functions that has not already
 * been closed. `error` must be NULL or point at a writable `gpkg_error_t`.
 */
gpkg_status gpkg_close(gpkg_t *gpkg, gpkg_error_t *error);

/**
 * The GeoPackage specification version the file declares, as `"1.0"` through
 * `"1.4"`.
 *
 * This is what the file's `application_id` and `user_version` pragmas say
 * about itself, which is not a statement that its contents conform to that
 * version.
 *
 * The returned string is owned by the caller and must be released with
 * `gpkg_string_free`. Returns NULL on failure.
 *
 * # Safety
 *
 * `gpkg` must be a live handle. `error` must be NULL or writable.
 */
char *gpkg_version(const gpkg_t *gpkg, gpkg_error_t *error);

/**
 * How many warnings a lenient open collected.
 *
 * Always 0 for a handle from `gpkg_open` or `gpkg_create`, which are strict,
 * and for a file `gpkg_open_read_only` found nothing to forgive in. Pair it
 * with `gpkg_open_warning`, which takes an index below this count.
 *
 * ```c
 * size_t warnings = gpkg_open_warning_count(gpkg);
 * for (size_t i = 0; i < warnings; i++) {
 *     char *warning = gpkg_open_warning(gpkg, i, &error);
 *     if (warning) {
 *         printf("warning: %s\n", warning);
 *         gpkg_string_free(warning);
 *     }
 * }
 * ```
 *
 * # Safety
 *
 * `gpkg` must be a live handle.
 */
size_t gpkg_open_warning_count(const gpkg_t *gpkg);

/**
 * One warning from a lenient open, as text, or NULL when `index` is out of
 * range.
 *
 * Each describes one thing the open tolerated: a legacy `application_id`, a
 * missing `gpkg_geometry_columns` table, a catalogue name matching its table
 * only case-insensitively, or an extension the library cannot identify.
 * `gpkg_open_warning_count` bounds the index.
 *
 * The returned string is owned by the caller and must be released with
 * `gpkg_string_free`.
 *
 * # Safety
 *
 * `gpkg` must be a live handle. `error` must be NULL or writable.
 */
char *gpkg_open_warning(const gpkg_t *gpkg, size_t index, gpkg_error_t *error);

/**
 * Whether a transaction is open on this handle.
 *
 * The way to ask before calling `gpkg_begin`, `gpkg_commit` or
 * `gpkg_rollback`, each of which refuses when the state is not what it needs.
 * `false` for a NULL handle, which has no transaction either.
 *
 * ```c
 * // On the way out of a function that may have failed part-way through.
 * if (gpkg_in_transaction(gpkg)) {
 *     gpkg_rollback(gpkg, NULL);
 * }
 * ```
 *
 * # Safety
 *
 * `gpkg` must be a live handle.
 */
bool gpkg_in_transaction(const gpkg_t *gpkg);

/**
 * Begin a transaction, so that several writes commit or fail together.
 *
 * Every write made through this handle until `gpkg_commit` or
 * `gpkg_rollback` joins this transaction, including the ones that would
 * otherwise manage their own: `gpkg_layer_write_arrow`,
 * `gpkg_layer_create_spatial_index`, `gpkg_tiles_put` and the rest. Nothing
 * they write is durable until the commit.
 *
 * ```c
 * if (gpkg_begin(gpkg, &error) != GPKG_STATUS_OK) {
 *     return fail("gpkg_begin", &error);
 * }
 * if (gpkg_layer_write_arrow(layer, &stream, 1000, NULL, &error) != GPKG_STATUS_OK) {
 *     gpkg_rollback(gpkg, NULL);   // discard the rows that did land
 *     return fail("gpkg_layer_write_arrow", &error);
 * }
 * if (gpkg_commit(gpkg, &error) != GPKG_STATUS_OK) {
 *     return fail("gpkg_commit", &error);
 * }
 * ```
 *
 * One consequence is worth stating: the `batch_size` argument the write calls
 * take stops bounding transactions while this is open, because every batch
 * belongs to this one. Passing a batch size is then a statement about memory
 * rather than about durability.
 *
 * A deferred transaction, matching what this library opens for itself, so
 * SQLite takes the write lock at the first write rather than here. Until then
 * another connection can still write to the file.
 *
 * Refuses with `GPKG_STATUS_INVALID_ARGUMENT` when a transaction is already
 * open, since SQLite does not nest them. `gpkg_in_transaction` asks without
 * provoking the error.
 *
 * Closing a handle with a transaction still open rolls it back, because that
 * is what SQLite does when the connection goes.
 *
 * # Safety
 *
 * `gpkg` must be a live handle from one of the open functions. `error` must be
 * NULL or point at a writable `gpkg_error_t`.
 */
gpkg_status gpkg_begin(gpkg_t *gpkg, gpkg_error_t *error);

/**
 * Commit the open transaction, making everything written since `gpkg_begin`
 * durable.
 *
 * Refuses with `GPKG_STATUS_INVALID_ARGUMENT` when no transaction is open,
 * rather than succeeding silently, so an unbalanced pair is reported where it
 * happens.
 *
 * # Safety
 *
 * As `gpkg_begin`.
 */
gpkg_status gpkg_commit(gpkg_t *gpkg, gpkg_error_t *error);

/**
 * Discard everything written since `gpkg_begin`.
 *
 * This is how a partly-failed sequence is undone: a write that fails part-way
 * through leaves what preceded it in the transaction, for the caller to keep
 * or discard. Schema changes go back too, since SQLite's DDL is transactional:
 * a spatial index dropped inside the transaction, along with its triggers and
 * its `gpkg_extensions` row, comes back.
 *
 * Refuses with `GPKG_STATUS_INVALID_ARGUMENT` when no transaction is open.
 * A cleanup path that cannot know either way should ask `gpkg_in_transaction`
 * first, or pass NULL for `error` and ignore the status.
 *
 * # Safety
 *
 * As `gpkg_begin`.
 */
gpkg_status gpkg_rollback(gpkg_t *gpkg, gpkg_error_t *error);

/**
 * Release the message an error holds, and reset its code to `GPKG_STATUS_OK`.
 *
 * Safe to call on an error that was never filled in, and safe to call twice:
 * the message pointer is cleared as it is freed. Passing NULL does nothing.
 *
 * ```c
 * gpkg_error_t error = {GPKG_STATUS_OK, NULL};
 * gpkg_t *gpkg = gpkg_open("places.gpkg", &error);
 * if (!gpkg) {
 *     fprintf(stderr, "%s\n", error.message ? error.message : "(no message)");
 *     gpkg_error_clear(&error);   // the message is freed here
 * }
 * // `error` is now back to {GPKG_STATUS_OK, NULL} and ready for reuse.
 * ```
 *
 * # Safety
 *
 * `error`, when non-NULL, must point at a `gpkg_error_t` this library filled
 * in, and its `message` must not have been freed by any other means.
 */
void gpkg_error_clear(gpkg_error_t *error);

/**
 * Open a feature layer by name.
 *
 * The name is a `gpkg_contents.table_name`, matched without regard to case,
 * as SQLite resolves table names. A name no row declares is
 * `GPKG_STATUS_NOT_FOUND`; a name that declares something other than a feature
 * layer, an attribute table or a tile pyramid, is
 * `GPKG_STATUS_INVALID_ARGUMENT`, with the message naming what was found.
 *
 * Opening reads the table's schema, so it is the expensive part of working
 * with a layer. Hold the handle for as long as the work lasts rather than
 * reopening per call.
 *
 * The returned handle borrows `gpkg`, which cannot be closed until the handle
 * is released with `gpkg_layer_free`.
 *
 * Returns NULL on failure.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle, `name` a NUL-terminated UTF-8
 * string, and `error` NULL or a writable `gpkg_error_t`.
 */
gpkg_layer_t *gpkg_layer_open(const gpkg_t *gpkg, const char *name, gpkg_error_t *error);

/**
 * Open an attribute (non-spatial) layer by name.
 *
 * The same call as `gpkg_layer_open` for a table `gpkg_contents` declares as
 * `attributes` rather than `features`. Such a table has no geometry column, so
 * `gpkg_layer_geometry_column` returns NULL for it and the bounding-box read
 * does not apply; everything else, including the Arrow read and write, works
 * the same way.
 *
 * # Safety
 *
 * As [`gpkg_layer_open`].
 */
gpkg_layer_t *gpkg_attributes_open(const gpkg_t *gpkg, const char *name, gpkg_error_t *error);

/**
 * Release a layer handle.
 *
 * The container it came from can be closed once every handle taken from it has
 * been freed, so this is what a `GPKG_STATUS_HANDLE_IN_USE` from `gpkg_close`
 * is asking for. Passing NULL does nothing, which lets a cleanup path free a
 * handle it may never have opened.
 *
 * An Arrow stream taken from this layer counts against the container in its
 * own right, so freeing the layer is not on its own enough to permit a close:
 * the stream has to be released too.
 *
 * # Safety
 *
 * `layer` must be NULL, or a handle from `gpkg_layer_open` or
 * `gpkg_attributes_open` that has not already been freed. The container it
 * came from must still be alive, which is guaranteed by `gpkg_close` refusing
 * while this handle exists.
 */
void gpkg_layer_free(gpkg_layer_t *layer);

/**
 * The layer's table name.
 *
 * Owned by the caller; release with `gpkg_string_free`.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
char *gpkg_layer_name(const gpkg_layer_t *layer, gpkg_error_t *error);

/**
 * The number of rows in the layer, written through `out`.
 *
 * A `SELECT count(*)` over the table, so it reads the table rather than a
 * stored figure and costs what that costs.
 *
 * # Safety
 *
 * `layer` must be a live handle, `out` must point at a writable `uint64_t`,
 * and `error` must be NULL or writable.
 */
gpkg_status gpkg_layer_count(const gpkg_layer_t *layer, uint64_t *out, gpkg_error_t *error);

/**
 * How many feature layers the file declares.
 *
 * Feature layers only: a table `gpkg_contents` declares as `attributes` or
 * `tiles` is not counted, and neither is a `features` row with no matching
 * `gpkg_geometry_columns` entry. `gpkg_layer_name_at` walks the same list,
 * which is ordered by table name.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle; `error` NULL or writable.
 */
gpkg_status gpkg_layer_names_count(const gpkg_t *gpkg, size_t *out, gpkg_error_t *error);

/**
 * The name of the `index`th feature layer, or NULL when out of range.
 *
 * The list is the one `gpkg_layer_names_count` counts, ordered by table name,
 * so the pair walks a file's layers. An index at or beyond the count is
 * `GPKG_STATUS_NOT_FOUND` rather than a failure to read.
 *
 * Owned by the caller; release with `gpkg_string_free`.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle; `error` NULL or writable.
 */
char *gpkg_layer_name_at(const gpkg_t *gpkg, size_t index, gpkg_error_t *error);

/**
 * Whether a layer holds features or attributes, as `"features"` or
 * `"attributes"`.
 *
 * Owned by the caller; release with `gpkg_string_free`.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
char *gpkg_layer_kind(const gpkg_layer_t *layer, gpkg_error_t *error);

/**
 * How many columns the layer's table has, geometry and primary key included.
 *
 * # Safety
 *
 * `layer` must be a live handle, `out` writable, `error` NULL or writable.
 */
gpkg_status gpkg_layer_column_count(const gpkg_layer_t *layer, size_t *out, gpkg_error_t *error);

/**
 * The name of the `index`th column, or NULL when out of range.
 *
 * Owned by the caller; release with `gpkg_string_free`.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
char *gpkg_layer_column_name(const gpkg_layer_t *layer, size_t index, gpkg_error_t *error);

/**
 * The declared SQL type of the `index`th column, exactly as the file spells
 * it, or the empty string for a column declared without one.
 *
 * The declared text rather than a parsed enum, because a GeoPackage may carry
 * a type outside the spec's vocabulary and this crate keeps such a column
 * rather than rejecting it. A caller wanting the spec's own names can compare
 * against them.
 *
 * Owned by the caller; release with `gpkg_string_free`.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
char *gpkg_layer_column_type(const gpkg_layer_t *layer, size_t index, gpkg_error_t *error);

/**
 * Whether the `index`th column is the primary key. `false` for an index out
 * of range, which [`gpkg_layer_column_count`] distinguishes.
 *
 * # Safety
 *
 * `layer` must be a live handle.
 */
bool gpkg_layer_column_is_primary_key(const gpkg_layer_t *layer, size_t index);

/**
 * The geometry column's name, or NULL for an attribute layer.
 *
 * A NULL return with `error` left at `GPKG_STATUS_OK` means the layer simply
 * has no geometry, which is not a failure.
 *
 * Owned by the caller; release with `gpkg_string_free`.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
char *gpkg_layer_geometry_column(const gpkg_layer_t *layer, gpkg_error_t *error);

/**
 * The geometry column's declared type, such as `"POINT"`, or NULL for an
 * attribute layer.
 *
 * Owned by the caller; release with `gpkg_string_free`.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
char *gpkg_layer_geometry_type(const gpkg_layer_t *layer, gpkg_error_t *error);

/**
 * The geometry column's spatial reference system id, written through `out`.
 *
 * The id is a `gpkg_spatial_ref_sys.srs_id`, which for a file written by this
 * library is the EPSG code. Returns `GPKG_STATUS_NOT_FOUND` for a layer with
 * no geometry column, leaving `out` untouched.
 *
 * # Safety
 *
 * `layer` must be a live handle, `out` writable, `error` NULL or writable.
 */
gpkg_status gpkg_layer_srs_id(const gpkg_layer_t *layer, int32_t *out, gpkg_error_t *error);

/**
 * The layer's extent, written through the four out-parameters.
 *
 * The bounds recorded in `gpkg_contents`, in the layer's own spatial reference
 * system. Where those bounds are unusable, they are measured from the
 * geometries and recorded, so this call can write to the file; on a read-only
 * handle it measures, returns the answer, and records nothing.
 *
 * Returns `GPKG_STATUS_NOT_FOUND` when the layer has no extent to report,
 * which is an empty layer or one with no geometry column, leaving the
 * out-parameters untouched.
 *
 * # Safety
 *
 * `layer` must be a live handle, the four out-parameters writable, and
 * `error` NULL or writable.
 */
gpkg_status gpkg_layer_extent(const gpkg_layer_t *layer,
                              double *min_x,
                              double *min_y,
                              double *max_x,
                              double *max_y,
                              gpkg_error_t *error);

/**
 * The spatial index's state, as `"absent"`, `"current"`, `"legacy trigger
 * set"` or `"stale"`.
 *
 * `"legacy trigger set"` is an index kept by the pre-1.4 triggers, which
 * corrupt an index under `UPSERT`; `"stale"` is a virtual table without its
 * triggers, or triggers without their table, which is what an interrupted
 * build leaves. `gpkg_layer_repair_spatial_index` puts either right.
 *
 * Owned by the caller; release with `gpkg_string_free`.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
char *gpkg_layer_spatial_index_status(const gpkg_layer_t *layer, gpkg_error_t *error);

/**
 * Whether a bounding-box query on this layer will use the spatial index.
 *
 * False for a `stale` or absent index: a desynchronised index is not trusted,
 * and the query falls back to a correct full scan. So this answers how a
 * bounding-box read will be served, not whether the file contains an RTree
 * table; `gpkg_layer_spatial_index_status` answers that.
 *
 * # Safety
 *
 * `layer` must be a live handle, `out` writable, `error` NULL or writable.
 */
gpkg_status gpkg_layer_has_spatial_index(const gpkg_layer_t *layer, bool *out, gpkg_error_t *error);

/**
 * Build the spatial index on a layer that has none.
 *
 * Creates the RTree virtual table, installs the GeoPackage 1.4 trigger set,
 * populates it from the rows already there, and registers the extension, all
 * in one transaction. Refuses with `GPKG_STATUS_ALREADY_EXISTS` when the
 * layer has an index, and with `GPKG_STATUS_NOT_FOUND` when it has no
 * geometry column or no single-column primary key to key the index on.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
gpkg_status gpkg_layer_create_spatial_index(const gpkg_layer_t *layer, gpkg_error_t *error);

/**
 * Drop the spatial index and its triggers.
 *
 * Removes the RTree virtual table, its triggers and its `gpkg_extensions`
 * row, in one transaction. A feature layer with no index is not an error:
 * there is nothing to remove and the call succeeds. Bounding-box reads still
 * work afterwards, as a full scan returning the same rows.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
gpkg_status gpkg_layer_drop_spatial_index(const gpkg_layer_t *layer, gpkg_error_t *error);

/**
 * Put a legacy or desynchronised spatial index right, rebuilding it and
 * installing the GeoPackage 1.4 trigger set.
 *
 * A layer with no index is left alone: an absent index is a choice rather
 * than a defect, and `gpkg_layer_create_spatial_index` is how one is asked
 * for.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
gpkg_status gpkg_layer_repair_spatial_index(const gpkg_layer_t *layer, gpkg_error_t *error);

/**
 * Read a layer as an Arrow C Data Interface stream.
 *
 * `out` is filled in with a stream the caller owns and must release through
 * its own `release` callback, as the C Data Interface specifies. The stream
 * borrows the layer's container: the container cannot be closed until the
 * stream has been released, exactly as for a layer handle.
 *
 * ```c
 * struct ArrowArrayStream stream;
 * memset(&stream, 0, sizeof(stream));
 * if (gpkg_layer_read_arrow(layer, &stream, &error) != GPKG_STATUS_OK) {
 *     return fail("gpkg_layer_read_arrow", &error);
 * }
 *
 * for (;;) {
 *     struct ArrowArray array;
 *     memset(&array, 0, sizeof(array));
 *     if (stream.get_next(&stream, &array) != 0) {
 *         fprintf(stderr, "get_next: %s\n", stream.get_last_error(&stream));
 *         break;
 *     }
 *     if (array.release == NULL) {
 *         break;   // end of stream
 *     }
 *     // ... consume array.length rows ...
 *     array.release(&array);
 * }
 * stream.release(&stream);
 * ```
 *
 * Rows arrive in primary-key order, in batches of up to 65,536 rows. A batch
 * whose geometry would cross a byte ceiling is emitted short of that, so a
 * layer of very large geometries still reads. The ceiling is the smaller of
 * 2 GB, which is as far as the geometry column's 32-bit Arrow offsets reach,
 * and a quarter of the machine's memory.
 *
 * A failure part-way through is reported the interface's way: `get_next`
 * returns non-zero and `get_last_error` has the detail. The `error`
 * out-parameter here covers only opening the stream.
 *
 * Batches come back on one thread. The threaded reader assigns key windows to
 * workers, which needs a second connection per worker; a stream handed to C is
 * pulled on the caller's thread instead.
 *
 * # Safety
 *
 * `layer` must be a live layer handle, `out` must point at writable storage
 * for an `ArrowArrayStream`, and `error` must be NULL or writable. The
 * returned stream must be used from the thread that created it.
 */
gpkg_status gpkg_layer_read_arrow(const gpkg_layer_t *layer,
                                  struct ArrowArrayStream *out,
                                  gpkg_error_t *error);

/**
 * Read the rows of a layer intersecting a bounding box, as an Arrow stream.
 *
 * The box is in the layer's own spatial reference system, and a row is
 * returned when its geometry's envelope intersects the box, edges included.
 * An envelope is not the geometry, so the rows are a superset of those that
 * actually intersect: testing the geometries themselves is the caller's, on
 * the WKB the stream carries.
 *
 * Served by the layer's RTree index when it has a usable one, and by a full
 * scan with the same filter otherwise, returning the same rows either way.
 * `gpkg_layer_has_spatial_index` says which it will be.
 *
 * ```c
 * struct ArrowArrayStream stream;
 * memset(&stream, 0, sizeof(stream));
 * if (gpkg_layer_read_arrow_in(layer, -7.0, 53.0, -6.0, 54.0, &stream, &error)
 *     != GPKG_STATUS_OK) {
 *     return fail("gpkg_layer_read_arrow_in", &error);
 * }
 * // Pulled and released exactly as gpkg_layer_read_arrow's stream is.
 * ```
 *
 * Fails with `GPKG_STATUS_NOT_FOUND` on a layer with no geometry column,
 * which has nothing to intersect.
 *
 * # Safety
 *
 * As [`gpkg_layer_read_arrow`].
 */
gpkg_status gpkg_layer_read_arrow_in(const gpkg_layer_t *layer,
                                     double min_x,
                                     double min_y,
                                     double max_x,
                                     double max_y,
                                     struct ArrowArrayStream *out,
                                     gpkg_error_t *error);

/**
 * Write an Arrow C Data Interface stream into a layer.
 *
 * Writing appends: every batch adds rows, and nothing here changes or removes
 * one that is already there. That is what a bulk load wants, and it is why
 * re-writing rows that carry their own feature ids fails on the primary key
 * rather than replacing them. To change or remove an existing feature, take a
 * `gpkg_writer_t` with `gpkg_layer_writer`.
 *
 * The stream's schema must name columns the layer has. A column the layer
 * does not have is refused rather than dropped, because discarding data a
 * caller asked to write would be worse than declining it; a column of the
 * layer the stream does not name is left to its default. A type the layer
 * cannot store is `GPKG_STATUS_INVALID_ARGUMENT`. Building the layer with
 * `gpkg_create_layer_from_arrow_schema` from the same schema is what makes
 * the two agree by construction.
 *
 * A stream column matching the layer's primary key supplies each row's fid,
 * and a NULL there has one assigned. A stream appending to a layer that
 * already holds rows should therefore omit that column, or carry NULLs in
 * it: a fid the table already holds fails the write.
 *
 * Takes ownership of `stream`, as the C Data Interface specifies for a moved
 * stream: it is released here whether the write succeeds or fails, and the
 * caller must not release it again. `out_rows`, when non-NULL, receives the
 * number of rows written.
 *
 * ```c
 * struct ArrowArrayStream data;
 * memset(&data, 0, sizeof(data));
 * if (gpkg_layer_read_arrow(src_layer, &data, &error) != GPKG_STATUS_OK) {
 *     return fail("gpkg_layer_read_arrow", &error);
 * }
 *
 * uint64_t written = 0;
 * // `data` is consumed here, and must not be released afterwards.
 * if (gpkg_layer_write_arrow(dst_layer, &data, 1000, &written, &error)
 *     != GPKG_STATUS_OK) {
 *     return fail("gpkg_layer_write_arrow", &error);
 * }
 * printf("wrote %llu rows\n", (unsigned long long)written);
 * ```
 *
 * `batch_size` is the rows per write transaction; `0` writes everything in
 * one transaction. Inside a transaction the caller opened with `gpkg_begin`
 * it bounds nothing, since every batch belongs to that one, and is then a
 * statement about how many rows are held at once rather than about
 * durability.
 *
 * A failure part-way through leaves whatever earlier batches have already
 * committed, so `batch_size` also decides how much a failed write can leave
 * behind: `0` leaves nothing, because there is one transaction. Inside a
 * caller's transaction nothing is durable until their commit, and
 * `gpkg_rollback` discards all of it.
 *
 * The layer's spatial index, where it has one, is brought up to date as part
 * of the write.
 *
 * # Safety
 *
 * `layer` must be a live layer handle, `stream` must point at a stream the
 * caller owns and has not released, `out_rows` must be NULL or writable, and
 * `error` must be NULL or writable.
 */
gpkg_status gpkg_layer_write_arrow(const gpkg_layer_t *layer,
                                   struct ArrowArrayStream *stream,
                                   size_t batch_size,
                                   uint64_t *out_rows,
                                   gpkg_error_t *error);

/**
 * Create a layer whose columns come from an Arrow schema.
 *
 * The schema is borrowed, not consumed: the caller still owns it and must
 * release it. This is what lets a C consumer copy a layer without any
 * schema-description API of its own, by taking the schema from the source
 * stream's `get_schema` and handing it straight here.
 *
 * ```c
 * struct ArrowArrayStream src_stream;
 * memset(&src_stream, 0, sizeof(src_stream));
 * gpkg_layer_read_arrow(src_layer, &src_stream, &error);
 *
 * struct ArrowSchema schema;
 * memset(&schema, 0, sizeof(schema));
 * src_stream.get_schema(&src_stream, &schema);
 * src_stream.release(&src_stream);   // the schema outlives the stream
 *
 * gpkg_add_epsg_srs(dst, 4326, &error);
 * if (gpkg_create_layer_from_arrow_schema(dst, "cities", &schema, true, &error)
 *     != GPKG_STATUS_OK) {
 *     schema.release(&schema);
 *     return fail("gpkg_create_layer_from_arrow_schema", &error);
 * }
 * schema.release(&schema);
 * ```
 *
 * The geometry column and its spatial reference system are taken from the
 * schema's GeoArrow metadata. The referenced SRS must already exist in the
 * destination; `gpkg_add_epsg_srs` puts one there. The geometry column is
 * declared `GEOMETRY` rather than the source's own type, because the GeoArrow
 * WKB encoding does not carry one.
 *
 * `spatial_index` asks for an RTree index over that column, which is the
 * usual choice for a layer that will be queried by bounding box.
 * `gpkg_layer_create_spatial_index` adds one later, and costs a pass over the
 * rows to do it.
 *
 * Fails with `GPKG_STATUS_ALREADY_EXISTS` when the file already has a table
 * of that name, and with `GPKG_STATUS_NOT_FOUND` when the schema names a
 * spatial reference system the file does not carry.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle, `name` a NUL-terminated UTF-8
 * string, `schema` a valid `ArrowSchema` the caller owns, and `error` NULL or
 * writable.
 */
gpkg_status gpkg_create_layer_from_arrow_schema(const gpkg_t *gpkg,
                                                const char *name,
                                                const struct ArrowSchema *schema,
                                                bool spatial_index,
                                                gpkg_error_t *error);

/**
 * Register an EPSG spatial reference system in the file.
 *
 * A layer cannot name an SRS the file does not carry, so this is what a C
 * consumer calls before creating one.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle and `error` NULL or writable.
 */
gpkg_status gpkg_add_epsg_srs(const gpkg_t *gpkg, int32_t code, gpkg_error_t *error);

/**
 * Open a tile pyramid by name.
 *
 * The name is a `gpkg_contents.table_name` whose row declares `tiles`.
 * A name no such row declares is `GPKG_STATUS_NOT_FOUND`, and a name that
 * declares something else is `GPKG_STATUS_INVALID_ARGUMENT`.
 *
 * Opening reads the tile matrix set and every zoom level's matrix, so the
 * handle answers `gpkg_tiles_extent`, `gpkg_tiles_zoom_level_count` and
 * `gpkg_tiles_matrix_at` without going back to the file.
 *
 * The returned handle borrows `gpkg`, which cannot be closed until the handle
 * is released with `gpkg_tiles_free`.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle, `name` a NUL-terminated UTF-8
 * string, and `error` NULL or writable.
 */
gpkg_tiles_t *gpkg_tiles_open(const gpkg_t *gpkg, const char *name, gpkg_error_t *error);

/**
 * Release a tile pyramid handle. Passing NULL does nothing.
 *
 * # Safety
 *
 * `tiles` must be NULL, or a handle from `gpkg_tiles_open` that has not
 * already been freed.
 */
void gpkg_tiles_free(gpkg_tiles_t *tiles);

/**
 * The pyramid's table name. Owned by the caller; release with
 * `gpkg_string_free`.
 *
 * # Safety
 *
 * `tiles` must be a live handle; `error` NULL or writable.
 */
char *gpkg_tiles_name(const gpkg_tiles_t *tiles, gpkg_error_t *error);

/**
 * How many tiles the pyramid holds, across every zoom level.
 *
 * # Safety
 *
 * `tiles` must be a live handle, `out` writable, `error` NULL or writable.
 */
gpkg_status gpkg_tiles_count(const gpkg_tiles_t *tiles, int64_t *out, gpkg_error_t *error);

/**
 * How many tiles the pyramid holds at one zoom level.
 *
 * `zoom_level` is the number a level carries, which `gpkg_tiles_matrix_at`
 * reports, not its position in the ladder. A level the pyramid does not
 * declare holds no tiles, so the answer is 0 rather than an error.
 *
 * # Safety
 *
 * As [`gpkg_tiles_count`].
 */
gpkg_status gpkg_tiles_count_at(const gpkg_tiles_t *tiles,
                                int64_t zoom_level,
                                int64_t *out,
                                gpkg_error_t *error);

/**
 * How many zoom levels the pyramid declares.
 *
 * The number of `gpkg_tile_matrix` rows, which bounds the `index` that
 * `gpkg_tiles_matrix_at` takes. A declared level may hold no tiles.
 *
 * # Safety
 *
 * `tiles` must be a live handle, `out` writable, `error` NULL or writable.
 */
gpkg_status gpkg_tiles_zoom_level_count(const gpkg_tiles_t *tiles,
                                        size_t *out,
                                        gpkg_error_t *error);

/**
 * One zoom level's matrix, by position in the declared ladder rather than by
 * zoom number, so a caller can walk them without guessing which exist.
 *
 * `index` runs from zero to `gpkg_tiles_zoom_level_count`, in ascending zoom
 * order, and `zoom_level` is the number the level actually carries, which is
 * what `gpkg_tiles_count_at`, `gpkg_tiles_get` and `gpkg_tiles_put` address
 * tiles by. `matrix_width` and `matrix_height` are the grid in tiles;
 * `tile_width` and `tile_height` are one tile in pixels.
 *
 * Any out-parameter may be NULL, in which case that field is not written.
 * An index beyond the last level is `GPKG_STATUS_NOT_FOUND`.
 *
 * # Safety
 *
 * `tiles` must be a live handle; every non-NULL out-parameter must be
 * writable; `error` NULL or writable.
 */
gpkg_status gpkg_tiles_matrix_at(const gpkg_tiles_t *tiles,
                                 size_t index,
                                 int64_t *zoom_level,
                                 int64_t *matrix_width,
                                 int64_t *matrix_height,
                                 int64_t *tile_width,
                                 int64_t *tile_height,
                                 gpkg_error_t *error);

/**
 * The pyramid's extent and spatial reference system.
 *
 * The `gpkg_tile_matrix_set` bounds: the ground area the grids are indexed
 * against, which is what makes a tile address mean a place. It is not a
 * statement about which tiles are present, since a pyramid may be sparse.
 *
 * Any out-parameter may be NULL.
 *
 * # Safety
 *
 * As [`gpkg_tiles_matrix_at`].
 */
gpkg_status gpkg_tiles_extent(const gpkg_tiles_t *tiles,
                              double *min_x,
                              double *min_y,
                              double *max_x,
                              double *max_y,
                              int32_t *srs_id,
                              gpkg_error_t *error);

/**
 * Whether a tile is stored at an address.
 *
 * Cheaper than fetching one to find out, since no payload is read. An address
 * no zoom level or grid contains is `false` rather than an error: it holds no
 * tile either.
 *
 * # Safety
 *
 * `tiles` must be a live handle, `out` writable, `error` NULL or writable.
 */
gpkg_status gpkg_tiles_has(const gpkg_tiles_t *tiles,
                           int64_t zoom_level,
                           int64_t column,
                           int64_t row,
                           bool *out,
                           gpkg_error_t *error);

/**
 * The bytes stored at a tile address.
 *
 * On success `out_data` receives an allocation the caller owns and must
 * release with `gpkg_bytes_free`, and `out_len` its length. A tile that is not
 * there is `GPKG_STATUS_NOT_FOUND` with `out_data` left NULL and `out_len`
 * zero, which is an ordinary answer for a sparse pyramid rather than a failure
 * to report, and no message is set for it.
 *
 * ```c
 * uint8_t *data = NULL;
 * size_t len = 0;
 * gpkg_status status = gpkg_tiles_get(tiles, 1, 0, 0, &data, &len, &error);
 * if (status == GPKG_STATUS_OK) {
 *     fwrite(data, 1, len, out);
 *     gpkg_bytes_free(data, len);   // exactly the length this call wrote
 * } else if (status != GPKG_STATUS_NOT_FOUND) {
 *     return fail("gpkg_tiles_get", &error);
 * }
 * ```
 *
 * `gpkg_tiles_get_into` is the alternative, and the better one for a caller
 * reading many tiles: it copies into the caller's own buffer, so no allocation
 * crosses the boundary and there is no length to keep hold of.
 *
 * The bytes are what the file holds. Nothing is decoded.
 *
 * # Safety
 *
 * `tiles` must be a live handle, `out_data` and `out_len` writable, and
 * `error` NULL or writable.
 */
gpkg_status gpkg_tiles_get(const gpkg_tiles_t *tiles,
                           int64_t zoom_level,
                           int64_t column,
                           int64_t row,
                           uint8_t **out_data,
                           size_t *out_len,
                           gpkg_error_t *error);

/**
 * Store bytes at a tile address.
 *
 * The address is checked against the zoom level's grid and the payload's
 * header against the tile size the level declares. Reading a header is not
 * decoding an image: what it catches is a tile of the wrong pixel size, or in
 * a format the table may not hold.
 *
 * ```c
 * if (gpkg_tiles_put(tiles, 1, 0, 0, png, png_len, &error) != GPKG_STATUS_OK) {
 *     return fail("gpkg_tiles_put", &error);
 * }
 * ```
 *
 * The bytes are copied into the file during the call, so the caller's buffer
 * is its own again on return. Writing where a tile is already stored replaces
 * it.
 *
 * A zoom level the pyramid does not declare is `GPKG_STATUS_NOT_FOUND`, and a
 * format the table may not hold is `GPKG_STATUS_UNSUPPORTED`. A column or row
 * outside the level's grid, and a payload whose header disagrees with the
 * declared tile size, are `GPKG_STATUS_OTHER`, with the message saying which:
 * these come from the tile checks, which have no category of their own.
 *
 * # Safety
 *
 * `tiles` must be a live handle, `data` must point at `len` readable bytes,
 * and `error` NULL or writable.
 */
gpkg_status gpkg_tiles_put(const gpkg_tiles_t *tiles,
                           int64_t zoom_level,
                           int64_t column,
                           int64_t row,
                           const uint8_t *data,
                           size_t len,
                           gpkg_error_t *error);

/**
 * Delete the tile at an address, reporting through `out_deleted` whether one
 * was there. `out_deleted` may be NULL.
 *
 * Deleting where there is no tile is success with `out_deleted` false, not an
 * error: the address is empty either way. The zoom level's `gpkg_tile_matrix`
 * row is left alone, so the level keeps its declared grid.
 *
 * # Safety
 *
 * `tiles` must be a live handle; `out_deleted` NULL or writable; `error` NULL
 * or writable.
 */
gpkg_status gpkg_tiles_delete(const gpkg_tiles_t *tiles,
                              int64_t zoom_level,
                              int64_t column,
                              int64_t row,
                              bool *out_deleted,
                              gpkg_error_t *error);

/**
 * Release a byte buffer this library returned.
 *
 * `gpkg_tiles_get` is the only call that hands one over, and its `out_len` is
 * the `len` to pass here. Passing a NULL pointer does nothing.
 *
 * Passing the wrong `len` is undefined behaviour, and not one a sanitizer can
 * be relied on to catch. A caller who would rather not carry the length
 * should use [`gpkg_tiles_get_into`], where no allocation crosses the
 * boundary and there is nothing to get wrong.
 *
 * # Safety
 *
 * `data` must be NULL, or a buffer from `gpkg_tiles_get` that has not already
 * been freed, and `len` must be the length that call wrote.
 */
void gpkg_bytes_free(uint8_t *data, size_t len);

/**
 * The bytes at a tile address, into a buffer the caller owns.
 *
 * The safer of the two readers, and the faster one for a caller reading many
 * tiles: no allocation crosses the boundary, so there is no ownership to get
 * wrong and no per-tile allocation. Backed by the library's own
 * `get_tile_into`, which reuses the buffer it is given.
 *
 * `out_len` always receives the tile's length when one is there, whether or
 * not it fitted. When `capacity` is too small the return is
 * `GPKG_STATUS_INVALID_ARGUMENT`, nothing is written, and `out_len` says how
 * much room the tile needs, so the usual shape is to call once with whatever
 * buffer is to hand and again if it was short.
 *
 * ```c
 * unsigned char buffer[64 * 1024];
 * size_t len = 0;
 * gpkg_status status =
 *     gpkg_tiles_get_into(tiles, 1, 0, 0, buffer, sizeof(buffer), &len, &error);
 *
 * if (status == GPKG_STATUS_INVALID_ARGUMENT) {
 *     gpkg_error_clear(&error);
 *     unsigned char *bigger = malloc(len);
 *     status = gpkg_tiles_get_into(tiles, 1, 0, 0, bigger, len, &len, &error);
 *     // ... use bigger ...
 *     free(bigger);
 * }
 * ```
 *
 * Passing NULL with a `capacity` of zero is allowed, and is how the length is
 * asked for on its own: nothing is copied, `out_len` holds what the tile
 * needs, and the return is the `GPKG_STATUS_INVALID_ARGUMENT` that any buffer
 * too small gets.
 *
 * A tile that is not there is `GPKG_STATUS_NOT_FOUND` with `out_len` zero, and
 * no message.
 *
 * # Safety
 *
 * `tiles` must be a live handle; `buffer` must point at `capacity` writable
 * bytes, or be NULL when `capacity` is zero; `out_len` must be writable; and
 * `error` NULL or writable.
 */
gpkg_status gpkg_tiles_get_into(const gpkg_tiles_t *tiles,
                                int64_t zoom_level,
                                int64_t column,
                                int64_t row,
                                uint8_t *buffer,
                                size_t capacity,
                                size_t *out_len,
                                gpkg_error_t *error);

/**
 * Release a string this library returned.
 *
 * Every call that returns a `char *` returns an allocation the caller owns,
 * so each one is paired with this. Passing NULL does nothing, which is what
 * makes the pairing safe to write before the failure has been checked:
 *
 * ```c
 * char *kind = gpkg_layer_kind(layer, &error);
 * if (kind) {
 *     printf("%s\n", kind);
 * }
 * gpkg_string_free(kind);
 * ```
 *
 * # Safety
 *
 * `text` must be NULL, or a string returned by this library that has not
 * already been freed.
 */
void gpkg_string_free(char *text);

/**
 * Begin a write transaction over `layer`.
 *
 * The writer borrows the layer's container, which cannot be closed while the
 * writer is alive. Finish with `gpkg_writer_commit`, or discard the work with
 * `gpkg_writer_free`.
 *
 * Returns NULL on failure. A read-only handle fails here rather than at the
 * first write.
 *
 * # Safety
 *
 * `layer` must be a live layer handle and `error` NULL or writable. The
 * returned writer must be destroyed exactly once, with `gpkg_writer_commit` or
 * `gpkg_writer_free`, on the thread that created it.
 */
gpkg_writer_t *gpkg_layer_writer(const gpkg_layer_t *layer, gpkg_error_t *error);

/**
 * Commit the writer's work and destroy it.
 *
 * The handle is destroyed whether this succeeds or fails, so it must not be
 * used again either way. Inside a transaction the caller opened with
 * `gpkg_begin`, this stages the work rather than committing it, and their
 * `gpkg_commit` is what makes it durable.
 *
 * # Safety
 *
 * `writer` must be a live writer handle that has not already been committed or
 * freed. `error` must be NULL or writable.
 */
gpkg_status gpkg_writer_commit(gpkg_writer_t *writer, gpkg_error_t *error);

/**
 * Discard the writer's work and destroy it.
 *
 * Everything staged since `gpkg_layer_writer` is rolled back. Inside a
 * transaction the caller opened, nothing is rolled back here: the work stays
 * staged in that transaction, and `gpkg_rollback` is what discards it.
 *
 * Freeing NULL does nothing.
 *
 * # Safety
 *
 * `writer` must be NULL, or a live writer handle that has not already been
 * committed or freed.
 */
void gpkg_writer_free(gpkg_writer_t *writer);

/**
 * Insert a feature, with or without a geometry.
 *
 * `fid` is NULL to have an id assigned, or points at the id to use. The id
 * written is reported through `out_fid` when that is non-NULL.
 *
 * `wkb` is the geometry, or NULL with `wkb_len` zero for a row with none.
 * `values` covers the layer's value columns in order; `values_len` must match
 * the layer.
 *
 * # Safety
 *
 * `writer` must be a live writer handle. `fid` must be NULL or readable.
 * `wkb` must be NULL or readable for `wkb_len` bytes. `values` must be NULL
 * (with `values_len` zero) or point at `values_len` readable values.
 * `out_fid` and `error` must be NULL or writable.
 */
gpkg_status gpkg_writer_insert(gpkg_writer_t *writer,
                               const int64_t *fid,
                               const uint8_t *wkb,
                               size_t wkb_len,
                               const gpkg_value_t *values,
                               size_t values_len,
                               int64_t *out_fid,
                               gpkg_error_t *error);

/**
 * Update the feature `fid`, replacing every value column and, when `wkb` is
 * given, the geometry.
 *
 * `out_matched` reports whether a row with that id was there to update; a
 * missing row is not an error.
 *
 * # Safety
 *
 * As [`gpkg_writer_insert`], with `out_matched` NULL or writable.
 */
gpkg_status gpkg_writer_update(gpkg_writer_t *writer,
                               int64_t fid,
                               const uint8_t *wkb,
                               size_t wkb_len,
                               const gpkg_value_t *values,
                               size_t values_len,
                               bool *out_matched,
                               gpkg_error_t *error);

/**
 * Update one column of the feature `fid`, leaving every other value and the
 * geometry alone.
 *
 * The shape a caller wants when correcting one field: nothing else has to be
 * supplied, and nothing else is touched.
 *
 * # Safety
 *
 * `writer` must be a live writer handle, `column` a NUL-terminated UTF-8
 * string, `value` a readable value, and `out_matched` and `error` NULL or
 * writable.
 */
gpkg_status gpkg_writer_update_column(gpkg_writer_t *writer,
                                      int64_t fid,
                                      const char *column,
                                      const gpkg_value_t *value,
                                      bool *out_matched,
                                      gpkg_error_t *error);

/**
 * Delete the feature `fid`.
 *
 * `out_matched` reports whether a row with that id was there to delete; a
 * missing row is not an error.
 *
 * The layer's recorded bounding box is not shrunk, here or anywhere else: an
 * over-estimate is what the specification permits, and shrinking would mean
 * rescanning the layer.
 *
 * # Safety
 *
 * `writer` must be a live writer handle, and `out_matched` and `error` NULL or
 * writable.
 */
gpkg_status gpkg_writer_delete(gpkg_writer_t *writer,
                               int64_t fid,
                               bool *out_matched,
                               gpkg_error_t *error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GEOPACKAGE_H */
