/* Generated by cbindgen from geopackage-ffi. Do not edit by hand.
 *
 * Regenerate with:
 *     cbindgen --config geopackage-ffi/cbindgen.toml \
 *              --crate geopackage-ffi \
 *              --output geopackage-ffi/include/geopackage.h
 *
 * CI regenerates it and fails if the result differs from what is committed, so
 * an ABI change cannot land without showing up as a diff in this file.
 */

#ifndef GEOPACKAGE_H
#define GEOPACKAGE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#ifndef ARROW_C_DATA_INTERFACE
#define ARROW_C_DATA_INTERFACE

#define ARROW_FLAG_DICTIONARY_ORDERED 1
#define ARROW_FLAG_NULLABLE 2
#define ARROW_FLAG_MAP_KEYS_SORTED 4

struct ArrowSchema {
  const char *format;
  const char *name;
  const char *metadata;
  int64_t flags;
  int64_t n_children;
  struct ArrowSchema **children;
  struct ArrowSchema *dictionary;
  void (*release)(struct ArrowSchema *);
  void *private_data;
};

struct ArrowArray {
  int64_t length;
  int64_t null_count;
  int64_t offset;
  int64_t n_buffers;
  int64_t n_children;
  const void **buffers;
  struct ArrowArray **children;
  struct ArrowArray *dictionary;
  void (*release)(struct ArrowArray *);
  void *private_data;
};

#endif  /* ARROW_C_DATA_INTERFACE */

#ifndef ARROW_C_STREAM_INTERFACE
#define ARROW_C_STREAM_INTERFACE

struct ArrowArrayStream {
  int (*get_schema)(struct ArrowArrayStream *, struct ArrowSchema *out);
  int (*get_next)(struct ArrowArrayStream *, struct ArrowArray *out);
  const char *(*get_last_error)(struct ArrowArrayStream *);
  void (*release)(struct ArrowArrayStream *);
  void *private_data;
};

#endif  /* ARROW_C_STREAM_INTERFACE */


/**
 * What kind of failure occurred.
 *
 * `#[repr(i32)]` so cbindgen emits a plain C enum with stable values. Values
 * are assigned explicitly and must never be reused for another meaning.
 */
enum gpkg_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * No error.
   */
  GPKG_STATUS_OK = 0,
  /**
   * The file could not be read or written: an I/O or SQLite failure.
   */
  GPKG_STATUS_IO = 1,
  /**
   * The file is not a GeoPackage, or not one this library can identify.
   */
  GPKG_STATUS_NOT_A_GEO_PACKAGE = 2,
  /**
   * A named table, layer, column, SRS or record is not there.
   */
  GPKG_STATUS_NOT_FOUND = 3,
  /**
   * Something the call would create is already there.
   */
  GPKG_STATUS_ALREADY_EXISTS = 4,
  /**
   * An argument was rejected: a bad value, a type mismatch, a malformed
   * geometry, or a count that does not line up.
   */
  GPKG_STATUS_INVALID_ARGUMENT = 5,
  /**
   * The file uses something this library does not implement.
   */
  GPKG_STATUS_UNSUPPORTED = 6,
  /**
   * A constraint the file or the schema declares was violated.
   */
  GPKG_STATUS_CONSTRAINT = 7,
  /**
   * A handle is still borrowing what the call would destroy. Free the child
   * handles first; nothing was changed.
   */
  GPKG_STATUS_HANDLE_IN_USE = 8,
  /**
   * A string argument was not valid UTF-8, or a required pointer was NULL.
   */
  GPKG_STATUS_BAD_ARGUMENT = 9,
  /**
   * Anything else. The message says what happened.
   */
  GPKG_STATUS_OTHER = 99,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum gpkg_status gpkg_status;
#else
typedef int32_t gpkg_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A `gpkg_t`: an open GeoPackage, and a count of the handles borrowing it.
 */
typedef struct gpkg_t gpkg_t;

/**
 * A `gpkg_layer_t`: a layer, and the container it borrows.
 */
typedef struct gpkg_layer_t gpkg_layer_t;

/**
 * An open GeoPackage. Opaque; created by `gpkg_open`, `gpkg_open_read_only` or
 * `gpkg_create`, and destroyed by `gpkg_close`.
 */
typedef gpkg_t gpkg_t;

/**
 * A failure, as C sees it.
 *
 * `code` is [`Status::Ok`] and `message` NULL when nothing went wrong. A
 * non-NULL `message` is an owned NUL-terminated UTF-8 string that the caller
 * must release with [`gpkg_error_clear`].
 */
typedef struct {
  /**
   * What kind of failure occurred.
   */
  gpkg_status code;
  /**
   * A human-readable description, or NULL. Owned by the caller once set.
   */
  char *message;
} gpkg_error_t;

/**
 * A layer of an open GeoPackage. Opaque; created by `gpkg_layer_open` or
 * `gpkg_attributes_open`, and destroyed by `gpkg_layer_free`.
 */
typedef gpkg_layer_t gpkg_layer_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open an existing GeoPackage read-write.
 *
 * Returns NULL on failure, with `error` filled in when it is non-NULL.
 *
 * # Safety
 *
 * `path` must be a valid pointer to a NUL-terminated UTF-8 string. `error`
 * must be NULL or point at a writable `gpkg_error_t`. The returned handle must
 * be destroyed with `gpkg_close`, on the thread that created it.
 */
gpkg_t *gpkg_open(const char *path, gpkg_error_t *error);

/**
 * Open an existing GeoPackage read-only, tolerating legacy and lightly
 * non-conforming files.
 *
 * # Safety
 *
 * As [`gpkg_open`].
 */
gpkg_t *gpkg_open_read_only(const char *path, gpkg_error_t *error);

/**
 * Create a new GeoPackage 1.4 file.
 *
 * # Safety
 *
 * As [`gpkg_open`].
 */
gpkg_t *gpkg_create(const char *path, gpkg_error_t *error);

/**
 * Close a GeoPackage and release its handle.
 *
 * Refuses with `GPKG_STATUS_HANDLE_IN_USE` while any layer handle taken from
 * it is still alive, in which case **the handle remains valid and open** and
 * the caller should free its layer handles first. On any other outcome the
 * handle is destroyed and must not be used again, including when this reports
 * a failure: the underlying file was released either way.
 *
 * For a handle that opted into WAL this checkpoints the WAL and resets the
 * journal mode, so the file is left as a single file with no sidecars.
 *
 * # Safety
 *
 * `gpkg` must be a handle from one of the open functions that has not already
 * been closed. `error` must be NULL or point at a writable `gpkg_error_t`.
 */
gpkg_status gpkg_close(gpkg_t *gpkg, gpkg_error_t *error);

/**
 * The GeoPackage specification version the file declares, as `"1.0"` through
 * `"1.4"`.
 *
 * The returned string is owned by the caller and must be released with
 * `gpkg_string_free`. Returns NULL on failure.
 *
 * # Safety
 *
 * `gpkg` must be a live handle. `error` must be NULL or writable.
 */
char *gpkg_version(const gpkg_t *gpkg, gpkg_error_t *error);

/**
 * How many warnings a lenient open collected.
 *
 * Always 0 for a handle from `gpkg_open` or `gpkg_create`, which are strict.
 *
 * # Safety
 *
 * `gpkg` must be a live handle.
 */
size_t gpkg_open_warning_count(const gpkg_t *gpkg);

/**
 * One warning from a lenient open, as text, or NULL when `index` is out of
 * range.
 *
 * The returned string is owned by the caller and must be released with
 * `gpkg_string_free`.
 *
 * # Safety
 *
 * `gpkg` must be a live handle. `error` must be NULL or writable.
 */
char *gpkg_open_warning(const gpkg_t *gpkg, size_t index, gpkg_error_t *error);

/**
 * Release the message an error holds, and reset it to [`Status::Ok`].
 *
 * Safe to call on an error that was never filled in, and safe to call twice:
 * the message pointer is cleared as it is freed. Passing NULL does nothing.
 *
 * # Safety
 *
 * `error`, when non-NULL, must point at a `gpkg_error_t` this library filled
 * in, and its `message` must not have been freed by any other means.
 */
void gpkg_error_clear(gpkg_error_t *error);

/**
 * Open a feature layer by name.
 *
 * The returned handle borrows `gpkg`, which cannot be closed until the handle
 * is released with `gpkg_layer_free`.
 *
 * Returns NULL on failure.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle, `name` a NUL-terminated UTF-8
 * string, and `error` NULL or a writable `gpkg_error_t`.
 */
gpkg_layer_t *gpkg_layer_open(const gpkg_t *gpkg, const char *name, gpkg_error_t *error);

/**
 * Open an attribute (non-spatial) layer by name.
 *
 * # Safety
 *
 * As [`gpkg_layer_open`].
 */
gpkg_layer_t *gpkg_attributes_open(const gpkg_t *gpkg, const char *name, gpkg_error_t *error);

/**
 * Release a layer handle.
 *
 * The container it came from can be closed once every handle taken from it has
 * been freed. Passing NULL does nothing.
 *
 * # Safety
 *
 * `layer` must be NULL, or a handle from `gpkg_layer_open` or
 * `gpkg_attributes_open` that has not already been freed. The container it
 * came from must still be alive, which is guaranteed by `gpkg_close` refusing
 * while this handle exists.
 */
void gpkg_layer_free(gpkg_layer_t *layer);

/**
 * The layer's table name.
 *
 * Owned by the caller; release with `gpkg_string_free`.
 *
 * # Safety
 *
 * `layer` must be a live handle; `error` NULL or writable.
 */
char *gpkg_layer_name(const gpkg_layer_t *layer, gpkg_error_t *error);

/**
 * The number of rows in the layer, written through `out`.
 *
 * # Safety
 *
 * `layer` must be a live handle, `out` must point at a writable `uint64_t`,
 * and `error` must be NULL or writable.
 */
gpkg_status gpkg_layer_count(const gpkg_layer_t *layer, uint64_t *out, gpkg_error_t *error);

/**
 * How many feature layers the file declares.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle; `error` NULL or writable.
 */
gpkg_status gpkg_layer_names_count(const gpkg_t *gpkg, size_t *out, gpkg_error_t *error);

/**
 * The name of the `index`th feature layer, or NULL when out of range.
 *
 * Owned by the caller; release with `gpkg_string_free`.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle; `error` NULL or writable.
 */
char *gpkg_layer_name_at(const gpkg_t *gpkg, size_t index, gpkg_error_t *error);

/**
 * Read a layer as an Arrow C Data Interface stream.
 *
 * `out` is filled in with a stream the caller owns and must release through
 * its own `release` callback, as the C Data Interface specifies. The stream
 * borrows the layer's container: the container cannot be closed until the
 * stream has been released, exactly as for a layer handle.
 *
 * Batches come back on one thread. The threaded reader assigns key windows to
 * workers, which needs a second connection per worker; a stream handed to C is
 * pulled on the caller's thread instead.
 *
 * # Safety
 *
 * `layer` must be a live layer handle, `out` must point at writable storage
 * for an `ArrowArrayStream`, and `error` must be NULL or writable. The
 * returned stream must be used from the thread that created it.
 */
gpkg_status gpkg_layer_read_arrow(const gpkg_layer_t *layer,
                                  struct ArrowArrayStream *out,
                                  gpkg_error_t *error);

/**
 * Read the rows of a layer intersecting a bounding box, as an Arrow stream.
 *
 * The columnar counterpart of a bounding-box query, returning the same rows a
 * scalar `features_in` would.
 *
 * # Safety
 *
 * As [`gpkg_layer_read_arrow`].
 */
gpkg_status gpkg_layer_read_arrow_in(const gpkg_layer_t *layer,
                                     double min_x,
                                     double min_y,
                                     double max_x,
                                     double max_y,
                                     struct ArrowArrayStream *out,
                                     gpkg_error_t *error);

/**
 * Write an Arrow C Data Interface stream into a layer.
 *
 * Takes ownership of `stream`, as the C Data Interface specifies for a moved
 * stream: it is released here whether the write succeeds or fails, and the
 * caller must not release it again. `out_rows`, when non-NULL, receives the
 * number of rows written.
 *
 * `batch_size` is the rows per write transaction; `0` writes everything in
 * one transaction.
 *
 * # Safety
 *
 * `layer` must be a live layer handle, `stream` must point at a stream the
 * caller owns and has not released, `out_rows` must be NULL or writable, and
 * `error` must be NULL or writable.
 */
gpkg_status gpkg_layer_write_arrow(const gpkg_layer_t *layer,
                                   struct ArrowArrayStream *stream,
                                   size_t batch_size,
                                   uint64_t *out_rows,
                                   gpkg_error_t *error);

/**
 * Create a layer whose columns come from an Arrow schema.
 *
 * The schema is borrowed, not consumed: the caller still owns it and must
 * release it. This is what lets a C consumer copy a layer without any
 * schema-description API of its own, by taking the schema from the source
 * stream's `get_schema` and handing it straight here.
 *
 * The geometry column and its spatial reference system are taken from the
 * schema's GeoArrow metadata. The referenced SRS must already exist in the
 * destination; `gpkg_add_epsg_srs` puts one there.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle, `name` a NUL-terminated UTF-8
 * string, `schema` a valid `ArrowSchema` the caller owns, and `error` NULL or
 * writable.
 */
gpkg_status gpkg_create_layer_from_arrow_schema(const gpkg_t *gpkg,
                                                const char *name,
                                                const struct ArrowSchema *schema,
                                                bool spatial_index,
                                                gpkg_error_t *error);

/**
 * Register an EPSG spatial reference system in the file.
 *
 * A layer cannot name an SRS the file does not carry, so this is what a C
 * consumer calls before creating one.
 *
 * # Safety
 *
 * `gpkg` must be a live container handle and `error` NULL or writable.
 */
gpkg_status gpkg_add_epsg_srs(const gpkg_t *gpkg, int32_t code, gpkg_error_t *error);

/**
 * Release a string this library returned.
 *
 * Passing NULL does nothing.
 *
 * # Safety
 *
 * `text` must be NULL, or a string returned by this library that has not
 * already been freed.
 */
void gpkg_string_free(char *text);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GEOPACKAGE_H */
